# -*- coding: utf-8 -*-
"""STOCK PROJECT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCV97IXPt5stSCpkvkdAsYC37AKRXAw2
"""

# Description: This program creates interactive candlesticks from the CSV file that is uploaded
import plotly.graph_objects as go # plotting library 
# Graph Objects - interactive charts 
import pandas as pd # pandas - data analysis library

from google.colab import files # upload the files 
uploaded = files.upload() # returns uploaded files

tesla = pd.read_csv('TSLA.csv') # reads the csv file 
# CSV - tabular format 
tesla = tesla.set_index(pd.DatetimeIndex(tesla['Date'].values)) # sets time stamp  
tesla # prints dataframe

figure = go.Figure( # creates the figure 
    data = [ # enter the data
            go.Candlestick( # candlestick chart 
                x = tesla.index, # tesla index
                low = tesla['Low'], # low price data 
                high = tesla['High'], # high price data 
                close = tesla['Close'], # close price data 
                open = tesla['Open'], # open price data 
                increasing_line_color = 'red', # create red boxes 
                decreasing_line_color = 'green' # create green boxes 
            )
    ]
)
figure.show() # show the figure